apiVersion: v1
kind: Pod
metadata:
  labels:
    name: vulcand
    version: v0.8.0-beta.3
  name: vulcand-v0.8.0-beta.3
  namespace: default
spec:
  containers:
    - image: mailgun/vulcand:v0.8.0-beta.3
      imagePullPolicy: Always
      name: vulcand
      command:
      - vulcand
      - -logSeverity=WARN
      - -etcd=http://YOUR_ETCD_HOST:2379
      - -etcd=http://YOUR_ETCD_HOST:2379
      - -apiInterface=0.0.0.0
      - -apiPort=8182
      - -interface=0.0.0.0
      - -port=80
      - -sealkey=YOUR_SEAL_KEY_USE_VCTL
      ports:
      - containerPort: 80
        hostPort: 80
        name: http
      - containerPort: 80
        hostPort: 80
        name: http
      - containerPort: 8182
      resources:
        limits:
          cpu: 75m
          memory: 256Mi
