apiVersion: v1
kind: Service
metadata:
  labels:
    name: vulcand
  name: vulcand
  namespace: default
spec:
  ports:
  - name: api
    port: 8182
    protocol: TCP
    targetPort: 8182
  selector:
    name: vulcand
