apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx
