apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx
    version: v1
  name: nginx-v1
  namespace: default
spec:
  replicas: 1
  selector:
    name: nginx
    version: v1
  template:
    metadata:
      labels:
        name: nginx
        version: v1
    spec:
      containers:
      - image: quay.io/galexrt/nginx-php-fpm:latest
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 75m
            memory: 512Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-www-storage
      volumes:
      - hostPath:
          path: /srv/docker/nginx/www
        name: nginx-www-storage
