apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: zabbix
  name: zabbix-web
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: zabbix-web
          servicePort: 80
