apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitlab
  name: gitlab
  namespace: default
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: gitlab
