apiVersion: v1
kind: Service
id: pxc-node1
metadata:
  name: pxc-node1
spec:
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic 
    - port: 4568
      name: incremental-state-transfer 
  selector:
    node: pxc-node1 
labels: 
  node: pxc-node1
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    node: pxc-node1
    unit: pxc-cluster
  name: pxc-node1
  namespace: default
spec:
  replicas: 1
  selector:
    node: pxc-node1
    unit: pxc-cluster
  template:
    metadata:
      labels:
        node: pxc-node1
        unit: pxc-cluster
    spec:
      containers:
      - args:
        - --skip-external-locking
        env:
        - name: GALERA_CLUSTER
          value: "true"
        - name: NUM_NODES
          value: "3"
        - name: WSREP_CLUSTER_ADDRESS
          value: "gcomm://"
        - name: WSREP_SST_USER
          value: "sst"
        - name: WSREP_SST_PASSWORD
          value: "RANDOM_USER_SST_PASSWORD"
        - name: MYSQL_USER
          value: "mysql"
        - name: MYSQL_PASSWORD
          value: "YOUR_MYSQL_USER_PASSWORD"
        - name: MYSQL_ROOT_PASSWORD
          value: "YOUR_MYSQL_ROOT_PASSWORD"
        image: capttofu/percona_xtradb_cluster_5_6:beta
        name: pxc-node1
        ports:
        - containerPort: 3306
          protocol: TCP
        - containerPort: 4444
          protocol: TCP
        - containerPort: 4567
          protocol: TCP
        - containerPort: 4568
          protocol: TCP
        resources:
          limits:
            cpu: 110m
            memory: 768Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - hostPath:
          path: /srv/docker/database/node1
        name: mysql-storage
