apiVersion: v1
kind: Service
metadata:
  name: pxc-node4
spec:
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic 
    - port: 4568
      name: incremental-state-transfer 
  selector:
    node: pxc-node4
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-node4
  labels:
    node: pxc-node4
    unit: pxc-cluster
spec:
  replicas: 1
  selector:
    node: pxc-node4
    unit: pxc-cluster
  template:
    metadata:
      labels:
        node: pxc-node4
        unit: pxc-cluster
    spec:
      containers:
      - args:
        - --skip-external-locking
        env:
        - name: GALERA_CLUSTER
          value: "true"
        - name: NUM_NODES
          value: "5"
        - name: WSREP_CLUSTER_ADDRESS
          value: "gcomm://"
        - name: WSREP_SST_USER
          value: "sst"
        - name: WSREP_SST_PASSWORD
          value: "dKoelMm+69ZDrEVLdLWvB1IPyWQ="
        - name: MYSQL_USER
          value: "mysql"
        - name: MYSQL_PASSWORD
          value: "CEQyq7dxuYf20pPU0/pt49AMwJ8="
        - name: MYSQL_ROOT_PASSWORD
          value: "7JDLIXcymYGLJad4iXQKx2SnlLA="
        image: capttofu/percona_xtradb_cluster_5_6:beta
        name: pxc-node1
        ports:
        - containerPort: 3306
          protocol: TCP
        - containerPort: 4444
          protocol: TCP
        - containerPort: 4567
          protocol: TCP
        - containerPort: 4568
          protocol: TCP
        resources:
          limits:
            memory: 1536Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - hostPath:
          path: "/mnt/data/docker/mysql-galera/node4"
        name: mysql-storage
