apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: sinusbot-1
    version: v0.9.8
  name: sinusbot-1-v0.9.8
  namespace: default
spec:
  replicas: 1
  selector:
    name: sinusbot-1
    version: v0.9.8
  template:
    metadata:
      labels:
        name: sinusbot-1
        version: v0.9.8
    spec:
      containers:
      - image: quay.io/galexrt/sinusbot:latest
        name: sinusbot-1
        ports:
        - containerPort: 8087
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 75m
            memory: 512Mi
        volumeMounts:
        - mountPath: /sinusbot/data
          name: sinusbot-data-storage
      volumes:
      - hostPath:
          path: /srv/docker/sinusbot-1/sinusbot-data-storage
        name: sinusbot-data-storage
