apiVersion: v1
kind: Service
metadata:
  labels:
    name: cachet
  name: cachet
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    name: cachet
