apiVersion: v1
kind: Service
metadata:
  labels:
    name: staytus
  name: staytus
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    name: staytus
